sudo: false
language: rust
cache:
  cargo: true
  directories:
    - "$VDPM_GIT_DIR"
    - "$SCCACHE_DIR"

addons:
  apt:
    packages:
    - libc6-i386
    - lib32stdc++6
    - lib32gcc1
    - patch

rust:
  - nightly

env:
  global:
    # sccache
    - CARGO_HOME="$HOME/.cargo"
    - RUSTC_WRAPPER="sccache"
    - SCCACHE_DIR="$HOME/.cache/sccache"
    # vitasdk
    - VDPM_GIT_DIR="$HOME/.cache/vdpm"
    - VITASDK="$HOME/.local/share/vitasdk"
    - PATH="$VITASDK/bin:$PATH"

install:
  - rustup component add rust-src
  - ci/travis/setup.sh
  - cargo install --debug xargo -f
  - mkdir -p target
  - curl -SsL "https://github.com/vita-rust/common/raw/master/armv7-vita-eabihf.json" > target/armv7-vita-eabihf.json

script:
  - cargo make build                                    # Compile natively
  - RUST_TARGET_PATH="$(pwd)/target" xargo build --release -vv --target armv7-vita-eabihf
  # - cargo make -lverbose xbuild                                   # Cross-compile
  # - cd examples/hello_rust_world  && cargo make vpk     # Build example VPK

# deploy:
#   provider: script
#   script: cargo make publish-flow
#   on:
#     tags: true
#     repo: vita-rust/psp2-sys
#     rust: stable

notifications:
  email:
  - althonosdev@gmail.com
